// <auto-generated />
using System;
using BlackJack.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackJack.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919022642_Check")]
    partial class Check
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlackJack.Domain.Models.Game.BlackjackTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("BlackjackTables");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentBet")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CurrentBetAmount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlayerId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TableId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.Spectator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Spectators");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GamesLost")
                        .HasColumnType("int");

                    b.Property<int>("GamesWon")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.BlackjackTable", b =>
                {
                    b.OwnsOne("BlackJack.Domain.Models.Game.Hand", "DealerHand", b1 =>
                        {
                            b1.Property<Guid>("BlackjackTableId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DealerCards");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsSoft")
                                .HasColumnType("bit")
                                .HasColumnName("DealerHandIsSoft");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DealerHandStatus");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DealerHandValue");

                            b1.HasKey("BlackjackTableId");

                            b1.ToTable("BlackjackTables");

                            b1.WithOwner()
                                .HasForeignKey("BlackjackTableId");
                        });

                    b.OwnsOne("BlackJack.Domain.Models.Betting.Money", "MaxBet", b1 =>
                        {
                            b1.Property<Guid>("BlackjackTableId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MaxBet");

                            b1.HasKey("BlackjackTableId");

                            b1.ToTable("BlackjackTables");

                            b1.WithOwner()
                                .HasForeignKey("BlackjackTableId");
                        });

                    b.OwnsOne("BlackJack.Domain.Models.Betting.Money", "MinBet", b1 =>
                        {
                            b1.Property<Guid>("BlackjackTableId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MinBet");

                            b1.HasKey("BlackjackTableId");

                            b1.ToTable("BlackjackTables");

                            b1.WithOwner()
                                .HasForeignKey("BlackjackTableId");
                        });

                    b.Navigation("DealerHand")
                        .IsRequired();

                    b.Navigation("MaxBet")
                        .IsRequired();

                    b.Navigation("MinBet")
                        .IsRequired();
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.Player", b =>
                {
                    b.OwnsOne("BlackJack.Domain.Models.Betting.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsMany("BlackJack.Domain.Models.Game.Hand", "Hands", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cards")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsSoft")
                                .HasColumnType("bit");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("PlayerId", "Id");

                            b1.ToTable("Players_Hands");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("Hands");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.Seat", b =>
                {
                    b.HasOne("BlackJack.Domain.Models.Game.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlackJack.Domain.Models.Game.BlackjackTable", null)
                        .WithMany("Seats")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.Spectator", b =>
                {
                    b.HasOne("BlackJack.Domain.Models.Game.BlackjackTable", null)
                        .WithMany("Spectators")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("BlackJack.Domain.Models.Users.PlayerId", "PlayerId", b1 =>
                        {
                            b1.Property<Guid>("SpectatorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PlayerId");

                            b1.HasKey("SpectatorId");

                            b1.ToTable("Spectators");

                            b1.WithOwner()
                                .HasForeignKey("SpectatorId");
                        });

                    b.Navigation("PlayerId")
                        .IsRequired();
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Users.UserProfile", b =>
                {
                    b.OwnsOne("BlackJack.Domain.Models.Betting.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("BlackJack.Domain.Models.Users.PlayerId", "PlayerId", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PlayerId");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("BlackJack.Domain.Models.Betting.Money", "TotalWinnings", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalWinnings");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("PlayerId")
                        .IsRequired();

                    b.Navigation("TotalWinnings")
                        .IsRequired();
                });

            modelBuilder.Entity("BlackJack.Domain.Models.Game.BlackjackTable", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Spectators");
                });
#pragma warning restore 612, 618
        }
    }
}
